version: '3'
services:
   hcp-annotate:
      build: .
      ports:
         - "8888:8888"
      volumes:
         - ${PWD}/hcpannot:/opt/ext/python/hcpannot
         - ${PWD}/save:/save
         - ${PWD}/.git:/home/jovyan/.extgit
      environment:
         - PYTHONPATH=/opt/ext/python
